os: osx
language: rust
rust:
- stable
cache: cargo
script:
- cargo build
- cargo test --color always
before_deploy:
- make release
deploy:
  provider: releases
  api_key:
    secure: kO7cHW4zpGh+35ZK7kLlT2pOpOFPwywjge4B8cjGJmTTcjVuXq2DHX73eblJDlOb/elv6lVBC0TZJ/24X666IhxW/fIM1iB6KfwrbzBjnm6Xp5g47DVXXIbWc63Z8ZBBuAWzn6K6bSzOKoL7DyMpwfxaE588EBxxOO0+5E8sX+a3OfbudskAkrQ4xfrEl27umT4BRogMurkbpKqYxmPH460ol95FYWckYdQ0JfhQSLPAl7YxS0uZqb6yIwO+NhwlooTLRxfTNSJ9eO+XnI2R424p+wQfM/66lCXND9MK53iEXM7Med+KkfD6ARu1xrmxCCS64x34yzs191S0oo0FzBsFPRheia7KTkFEMLbH/7449JPOpAw5dcQEPg6+MR9BXDC/PnG5kqP6RfVmFp8hZgAv+08gZungyzvS6lddGJufqBlHCwEGbs66xa0QsMRyyfAv/h6W/HwpjUMbAW86hGhq0Y+7LdyGjmq+Zv2fcSONpQ/+LMMP8jZg7evXSXyLSO6jEFhTY6/5jmHXclGkNQZBQGA8WC2vcklUZnt7Qpbd0iXR5Dnd8YLDfUWs3b0p5BDX+Z0YrfazSqSPiPn4XTW4x549G0boTu6KQjoF0/q8kQHVnJDu77TWgmYYexLFFDEM3jeWUa2rzgNfohTpZ7djIVYz4jikXeQx8dfr6IU=
  file: gems.alfredworkflow
  skip_cleanup: true
  on:
    tags: true
